// android/build.gradle

buildscript {

    ext {

        kotlin_version = "2.1.0"

        agp_version = "8.7.0"

        ndk_version = "27.0.12077973"

        compile_sdk = 35

        min_sdk = 26

        target_sdk = 35

    }

    repositories {

        google()

        mavenCentral()

    }

    dependencies {

        classpath "com.android.tools.build:gradle:$agp_version"

        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

    }

}

allprojects {

    repositories {

        google()

        mavenCentral()

    }

}

tasks.register("clean", Delete) {

    delete rootProject.buildDir

}