name: TamerCAD Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:

  typescript-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: tamercad-build
          path: dist/